tmon: fix do_compile failed when enable template/ima
Issue: LIN1019-3132

Fix error:
tmon.h:42:17: error: field 'tv' has incomplete type

There is a line in Makefile:
override CFLAGS += $(shell $(PKG_CONFIG) --cflags $(STATIC) panelw ncursesw

previously, tmon don't depend on pkg-config, so this line
don't actually work. when enable template/ima, tmon will
DEPENDS on sbsigntool-native, which depends on pkgconfig-native,
so that pkg-config will be populated into recipe-sysroot-native.
then above line in Makefile works, and get CFLAGS -D_XOPEN_SOURCE=600
XOPEN_SOURCE used by ncurse lib for wide-character features, which
will make glibc strict to this namespace, so some defination will
missing.

Fix by remove lines for get cflags of ncursesw.

Signed-off-by: Changqing Li <changqing.li@windriver.com>