Revert "kernel: Switch kernel to linux-yocto for LTS18 branches"
Issue: LIN1019-10

This reverts commit f84df8dc2d055c16ad4c197cd9f61e4b76c26ddb.

intel-x86 branch master-wr was mistakenly merged from WRLINUX_10_18_BASE by
"Merge branch 'master-wr' into WRLINUX_10_18_BASE". And thus "kernel: Switch
kernel to linux-yocto for LTS18 branches" was brought in and caused the
following build failure.

...
ERROR: Nothing PROVIDES 'virtual/kernel'
...

Signed-off-by: He Zhe <zhe.he@windriver.com>