rtl8723bs: Fix build with usrmerge
When using DISTRO_FEATURE += "usrmerge" the following error occurs.

ERROR: rtl8723bs-bt-git-r0 do_package_qa: QA Issue: rtl8723bs-bt package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
ERROR: rtl8723bs-bt-git-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: rtl8723bs-bt-git-r0 do_package_qa: Function failed: do_package_qa

This is fixed by using ${nonarch_base_libdir} instead of direct references to /lib.

Issue: LIN1018-4373

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>